# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main
- develop


pool:
  vmImage: ubuntu-latest

stages:
- stage: "Build"
  jobs:
    - job:  
      steps:
      - task: SecretsManagerGetSecret@1
        inputs:
          awsCredentials: 'awsConection'
          regionName: 'us-west-1'
          secretIdOrName: 'username'
          variableName: 'username'
      - task: SecretsManagerGetSecret@1
        inputs:
          awsCredentials: 'awsConection'
          regionName: 'us-west-1'
          secretIdOrName: 'password'
          variableName: 'password'
      - bash: echo $(username)
      - task: Docker@2
        inputs:
          command: 'build'
          Dockerfile: '**/Dockerfile'
          repository: 'backnodejs'
          tags: $(Build.BuildId)
          arguments: '--build-arg host=$(host) --build-arg port=$(port) --build-arg database=$(database) --build-arg user=$(username) --build-arg password=$(password)'
      - task: ECRPushImage@1
        inputs:
          awsCredentials: 'awsConection'
          regionName: 'us-east-1'
          sourceImageName: 'backnodejs'
          sourceImageTag: '$(Build.BuildId)'
          repositoryName: 'app-runner-rds-registry'
          pushTag: '$(Build.BuildId)'
- stage: "deploy"
  jobs:
    - job:  
      steps:
        - task: DownloadSecureFile@1
          name: caCertificate
          displayName: 'Download CA certificate'
          inputs:
            secureFile: 'configdeploy.json'
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(Agent.TempDirectory)'
            Contents: 'configdeploy.json'
            TargetFolder: '$(Build.SourcesDirectory)'
            CleanTargetFolder: false
            overWrite: false
            flattenFolders: false
            preserveTimestamp: true
          displayName: 'Copying configdeploy.json'
        - pwsh: |
              $jsonConfig=Get-Content -Raw -Path configdeploy.json | ConvertFrom-Json 
              $jsonConfig.SourceConfiguration.ImageRepository.ImageIdentifier="${env:ECRREPOSITORY}:${env:BUILD_BUILDID}"
              $newJson = $jsonConfig | ConvertTo-Json -depth 100
              $newJson | Set-Content configdeploy1.json
          displayName: "config Image for Json"
        - task: AWSCLI@1
          inputs:
            awsCredentials: 'awsConection'
            regionName: 'us-east-1'
            awsCommand: 'aws apprunner update-service     --cli-input-json file://configdeploy.json'
          displayName: "Deploy to App Runner"